// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlbassrxuoabgjqxnxox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsYmFzc3J4dW9hYmdqcXhueG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NzI5NzIsImV4cCI6MjA1MzU0ODk3Mn0.2EETkb1jwuH1HgJcUkTrlkLELbvJyrCJ3_Phc0JZSjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);